// DONT TOUCH !!Chisaki JS start from here
document.querySelector(".title").innerHTML += TitleUI("#FFFFFF","#1BA68F","Top 3 Mental illness in US","#1BA68F");
document.querySelector(".card").innerHTML += CardUI("What is top 1 Mental illness ?", "Bipolar disorder", "Anxiety disorder", "Major depressive disorder","Anxiety disorder","Symptoms can include excessive worrying, feeling agitated, <strong>restlessness, fatigue, tense muscles, difficulty sleeping, and panic attacks");
document.querySelector(".card").innerHTML += CardUI("What is 2nd Mental illness ?", "Bipolar disorder", "Anxiety disorder", "Major depressive disorder","Major depressive disorder", "Symptoms include depressed mood, change in weight, appetite and sleep patterns, fatigue, and a feeling of worthlessness");
document.querySelector(".card").innerHTML += CardUI("What is 3rd Mental illness ?", "Bipolar disorder", "Anxiety disorder", "Major depressive disorder","Bipolar disorder","Symptoms  include experience manic episodes where their moods and behaviors are drastically different than normal.");
document.querySelector(".title2").innerHTML += TitleUI("#FFFFFF","#FFD4C1","How to improve your mental health?","#FFAA81");
document.querySelector(".icon").innerHTML += IconUI("icon1",'comps/icon/pic1.svg',"EAT WELL");
document.querySelector(".icon").innerHTML += IconUI("icon2",'comps/icon/pic2.svg',"STRECHING");
document.querySelector(".icon").innerHTML += IconUI("icon3",'comps/icon/pic3.jpg',"STOP TOBBACO");
document.querySelector(".icon").innerHTML += IconUI("icon4",'comps/icon/pic4.svg', "TREAT YOURSELF");
document.querySelector(".icon").innerHTML += IconUI("icon5",'comps/icon/pic5.svg', "CHAT CHAT CHAT");
document.querySelector(".icon").innerHTML += IconUI("icon6",'comps/icon/pic6.svg', "PLAN YOUR GOAL");
document.querySelector(".info").innerHTML += InfoUI("info1",'comps/icon/pic1.svg',"Eat and drink to optimize your health","Eating healthy is not only good for your physical health, but also for your mental health. some people release their stress by eating junk foods, taking caffeine, or drinking alcohol, but it is not a good way to release your stress in the long run. Consider making healthy eating and drinking habits. ");
document.querySelector(".info").innerHTML += InfoUI("info2",'comps/icon/pic2.svg',"Exercise regularly","Try to do some exercises because we can ease our stress by moving our body. You can try non-competitive exercises, such as aerobics, weight training, and yoga. According to the study, aerobic exercise can release endorphins which are natural substances that make your feeling better and keep you being positive.");
document.querySelector(".info").innerHTML += InfoUI("info3",'comps/icon/pic3.jpg',"Stop using tobacco and nicotine products","Did you know smoking is not only bad for your physical health, but also mental health? Smoking increases your anxiety and tension. In fact, if you try to stop smoking and get rid of the nicotine, you would feel irritable and anxious due to the signals from certain chemicals in the brain.");
document.querySelector(".info").innerHTML += InfoUI("info4",'comps/icon/pic4.svg', "Study and practice relaxation techniques", "Finding your relaxation way is really important to relieve your stress. It can be anything that you would like to do, such as taking a long bath, deep breathing, doing mindfulness meditation, or daydreaming. In retheraphy, we are also introducing some popular relaxation ways.");
document.querySelector(".info").innerHTML += InfoUI("info5",'comps/icon/pic5.svg', "Talk how you feel to someone","By talking your concerns to someone else, you can organize your feeling. Moreover, someone may give you some advice for your concerns. It is always a good idea to talk your feelings to people you trust. If your concerns are really personal ones, you can also reach out to some professional consultants.");
document.querySelector(".info").innerHTML += InfoUI("info6",'comps/icon/pic6.svg', "Set realistic goals and expectations", "By setting realistic goals and achieving small goals step by step, you can get more and more confident on yourself. For example, if you are trying to go on diet, you can start by walking 1 or 2 bus stops distance once or twice a week. When you making a plan, it is a good idea to consider your plan for the long run.");
// DONT TOUCH !!Chisaki JS End here